### ISSUE TITLE
TerraformおよびAWS CLI実行環境をDockerで構築する

### ISSUE THREAD

**Issue by OnoYuta** [OnoYuta/laravel-blog-sample-infrastructure#1]
/cc @

- [x] 一つのissueで複数の問題を扱っていない
- [x] タイトルは簡潔で説明的か
- [x] Markdown形式で書かれている

## Context

- TerraformおよびAWS CLI実行環境

## Problem

- TerraformおよびAWS CLIのバージョン違いなどの環境差分を抑えたい

## Solution

[AWS CLI v2 Docker image](https://aws.amazon.com/jp/blogs/developer/aws-cli-v2-docker-image/)

[3. docker上でのTerraform実行について](https://www.sbcloud.co.jp/help/best-practice/terraform/06/docker/index.html#3-docker上でのterraform実行について)
[docker-composeで環境変数を設定する](https://qiita.com/reflet/items/a96752b4cd3838ea6932)

**Comment by OnoYuta** [comment]
## terraform実行環境

### terraform.tfvarsに環境変数を設定

terraform.tfvars

```
access_key = "MY_ACCESS_KEY"
secret_key = "MY_SECRET_KEY"
region     = "ap-northeast-1"
```

### .gitignoreにtfvarsを追加

```
*.tfvars // 追記
```

### docker-compose.ymlにterraformを追加

```
services:
  terraform:
    image: hashicorp/terraform:0.12.24
    working_dir: "/terraform"
    volumes:
      - ".:/terraform"
```

### provider.tfを作成

```
variable "access_key" {}
variable "secret_key" {}
variable "region" {}

provider "aws" {
  access_key = var.access_key
  secret_key = var.secret_key
  region     = var.region
}
```

### terraformコマンド実行

sample.tfを作成

```
resource "aws_vpc" "vpc" {
  instance_tenancy = "default"
  cidr_block       = "192.168.1.0/24"
}
```

コマンドを実行

```
docker-compose run --rm terraform apply 
~~
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by OnoYuta** [comment]
## AWS CLI実行環境

### docker-compose.ymlにawscliを追加

```
services:
~~
  awscli:
    image: amazon/aws-cli:latest
    working_dir: "/workdir"
    volumes:
      - ".aws:/root/.aws"
```

### 接続情報を登録

.aws/credentials

```
[default]
aws_access_key_id = MY_ACCESS_KEY
aws_secret_access_key = MY_SECRET_KEY
```

### .gitignoreに.aws/を追加

```
.aws/
```

### awsコマンドを実行

```
docker-compose run --rm awscli s3 ls                                                         
2020-06-09 12:23:44 laravel-blog-sample-bucket
2020-06-09 21:29:28 laravel-blog-sample-private-bucket
```
