### ISSUE TITLE
GitHub ActionsでTerraform CI環境を構築する

### ISSUE THREAD

**Issue by OnoYuta** [OnoYuta/laravel-blog-sample-infrastructure#2]
/cc @

- [x] 一つのissueで複数の問題を扱っていない
- [x] タイトルは簡潔で説明的か
- [x] Markdown形式で書かれている

## Context

- Terraform CI環境

## Problem

masterブランチへpushをトリガーに下記を自動実行したい

- terraform fmt
- terraform init
- terraform validate
- terraform plan

## Solution

[GitHub Actions上でTerraform CI/CD環境を構築する](https://qiita.com/yamashun/items/750e016e74b92691cec8)

**Comment by OnoYuta** [comment]
## .github/workflows/terraform.yml

```
name: 'Terraform GitHub Actions'
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_access_key:  ${{ secrets.TERRAFORM_ACCESS_KEY_ID }}
      TF_VAR_secret_key:  ${{ secrets.TERRAFORM_SECRET_ACCESS_KEY }}
      TF_VAR_region:  ${{ secrets.TERRAFORM_REGION }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: 'fmt'
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: 'init'
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: 'validate'
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.17
          tf_actions_subcommand: 'plan'
```

### Secret変数を設定

GitHubのSettings > Secretsより接続情報等を設定
